### ISSUE TITLE
Add ability to optionally listen to keys in select, input or textareas (currently they are always ignored)

### ISSUE THREAD

**Issue by gadfly361** [gadfly361/re-pressed#1]
Currently, all keys are ignored if pressed inside of a select, input, or textarea. However, it would be useful to be able to record and dispatch off of certain keys (like enter, arrows, or tab, etc.).

I think the solution here is to either:
- add a whitelist of keys that are *never* ignored, like `{:always-listen-keys [{:which 13}]`
- add flags to listen to select, input, and textarea, like `{:ignore-select? false}`, where it defaults to true.

**Comment by gadfly361** [comment]
Decided to go with the `:always-listen-keys` approach.

**Comment by sveri** [comment]
Thats awesome, I just ran into this using enter on a form with the older version and wondered how to make that work. 
Its a needed addition, thanks.
