### ISSUE TITLE
Registering `re-frame.core/trim-v` breaks `re-pressed`

### ISSUE THREAD

**Issue by ClemRz** [gadfly361/re-pressed#11]
```
(reg-global-interceptor trim-v)
```

This won't let re-pressed work.
I am not sure if this is re-pressed concern but I believe there might be a way to make it compatible.

**Comment by gadfly361** [comment]
@ClemRz Can you provide a minimal code snippet to reproduce?  Also, if you know of a way to make it compatible, I am happy to look at a suggestion.

**Comment by ClemRz** [comment]
I don't have a code snippet, but if you introduce that line at the bottom of your `/src/demo/re_pressed/events.cljs` you'll see what I'm talking about:
```
(reg-global-interceptor trim-v)
```

The thing is that I don't know if it's better to (A) adapt re-pressed to both cases (with and without trim-v as a global int) - or (B) the users (like me) should make sure they delimit the scope of their global interceptors (requires a bit of customization).

If you think we want to go down the (A) road then yes, I might spend a bit of time looking into a solution :)

**Comment by ClemRz** [comment]
After a quick discussion on [Clojurians' `re-frame` Slack channel](https://clojurians.slack.com/archives/C073DKH9P/p1613754195181800?thread_ts=1613752786.181000&cid=C073DKH9P) I admit that one should not register `trim-v` globally. Which means that this issue can be ignored and closed.

**Comment by gadfly361** [comment]
@ClemRz Thanks for opening an issue and also for looking for feedback within the community to help us get to a resolution. Much appreciated 🎉
