### ISSUE TITLE
re-frame: Subscribe was called outside of a reactive context

### ISSUE THREAD

**Issue by WeissP** [gadfly361/re-pressed#13]
Hi, I am not sure if it is a bug. But whenever I press keys in an `input` element, a warning `re-frame: Subscribe was called outside of a reactive context` occurs.

To reproduce:
1. run command `lein new re-frame <app-name> +re-pressed`
2. change `main-panel` in `views.cljs` to 
```clojure
(defn main-panel [] [:input])
```
3. press a key in the input element

**Comment by gadfly361** [comment]
@WeissP thanks for reporting this issue.

I am open to reviewing PRs if you or anyone reading this thread is interested in helping fix this.

**Comment by gadfly361** [comment]
There is a [fork of re-pressed](https://github.com/M-sleeper/re-pressed) that fixes this issue. Note: there are trade-offs between this repo and the fork. This repo has the console warnings described in this issue but guarantees event ordering, while the fork fixes the console warnings, but doesn't guarantee event ordering.
