### ISSUE TITLE
Remove jquery from dependencies

### ISSUE THREAD

**Issue by khmelevskii** [gadfly361/re-pressed#6]
Thank you for this library but to include jquery to modern react app is not the best practice. This lib will be nicer for me when it doesn't not depend on jquery

**Comment by gadfly361** [comment]
@khmelevskii Thanks for bringing this up! I can definitely understand why there would be a reluctance to depend on jQuery. 

However, given the number of browsers and varying versions out there, I think jQuery does the best in terms of cross-browser support and *normalizing* their api onto `which`.  For that reason, unfortunately, I do not intend to remove jQuery.

**Comment by rrrnld** [comment]
Sorry for commenting on a closed issue, but I was just about to open a similar one. Care to elaborate what jQuery exactly does better than the Closure Library? I just feel like pulling in all of jQuery to normalize keypresses is a bit heavy.

**Comment by gadfly361** [comment]
@heyarne Thanks for the follow up!

When using vanilla javascript, there are several ways to figure out what key was pressed (keyCode, key, which, etc). However, there is varying degrees of browser support for each of the options, the best options of today are deprecated by the web standards, and there is no one standard. To my understanding, jQuery creates a standard on `which` and makes is supported across browsers (so it isn't just exposing which directly, it is augmenting it to make sure it is consistent across browsers). This enables re-pressed to create an api on top of jQuery's `which` return values that it can rely upon.

If goog closure library provides a _standardized_ way to figure out what key was pressed that works across all major browsers (that isn't just exposing keyCode, key, which, etc. directly), I'd be happy to look at this further.  If that is the case, please point me to the documentation (I am not too familiar with the goog closure).

As an aside, the heaviness of jQuery is a reasonable concern. I wonder if there is a way to only pull in part of jQuery to support this feature? :thinking:

**Comment by rrrnld** [comment]
Without having looked into it too closely, Google Closure library does seem to normalize the key events across browsers, see [here](https://github.com/google/closure-library/blob/master/closure/goog/events/keyhandler.js#L211) for example. There is also a longer text on what they do in the [file header](https://github.com/google/closure-library/blob/master/closure/goog/events/keyhandler.js#L16).

I'm not too familiar with google closure myself, I just remember David Nolan selling bundling Google Closure with Clojurescript with cross-browser compatibility down to IE6. Maybe this helps!

**Comment by gadfly361** [comment]
@heyarne Awesome, this definitely looks promising! I am going to reopen this issue and give it some more thought.

**Comment by gadfly361** [comment]
Fixed in #7 by @heyarne :+1:
